export const S = {
  appName: "Prompt Canvas",
  loginTitle: "로그인",
  loginSubtitle: "개인 생성 라이브러리",
  email: "이메일",
  password: "비밀번호",
  signIn: "들어가기",
  signUp: "계정 만들기",
  signOut: "로그아웃",
  or: "또는",
  loginError: "로그인에 실패했어요. 이메일과 비밀번호를 확인해 주세요.",
  signupError: "계정을 만들지 못했어요. 이미 있는 이메일일 수 있어요.",
  needAuth: "계속하려면 로그인해 주세요.",

  searchPlaceholder: "검색 또는 명령…",
  upload: "업로드",
  canvas: "캔버스",
  library: "그리드",
  glossary: "용어집",
  glossarySoon: "용어집은 2단계에서 열립니다.",

  filterMore: (n: number) => `+${n}`,
  localMode: "로컬 모드 — 이 브라우저에만 저장됩니다",
  cloudMode: "클라우드에 저장 중",

  peopleBoard: "인물",
  peopleBoardEmoji: "✧",
  peopleHint: "인물을 올려 두고 성별·외모로 걸러 보세요. 이름은 캐릭터로 저장하면 됩니다.",
  wardrobeBoard: "의상",
  wardrobeBoardEmoji: "✦",
  wardrobeHint: "핀터레스트 의상 영감을 올려두고 아이템·갬성·색감으로 빠르게 찾으세요.",
  saveCharacter: "캐릭터로 저장",
  characterName: "캐릭터 이름",
  characterNamePh: "예: 유나, 민준",
  characterSaved: "캐릭터를 저장했어요",
  savedCharacters: "저장된 캐릭터",
  noCharacters: "아직 저장한 캐릭터가 없어요",
  moreFilters: "필터",
  assemblePrompt: "프롬프트 조립",
  basePrompt: "기본 프롬프트",
  basePromptPh: "이 캐릭터를 다시 그릴 때 붙일 문장",
  peopleAttrs: "인물 정보",
  deleteCharacter: "캐릭터 삭제",
  analyzeWardrobe: "의상 분류",
  wardrobeAiSoon: "의상 AI 분류는 다음 단계에서 자동으로 붙습니다.",
  wardrobeSection: "의상 분류",
  wardrobeFilters: "의상 필터",
  noWardrobeAssets: "아직 저장한 의상 영감이 없어요.",
  newBoard: "새 보드",
  boardName: "보드 이름",
  defaultBoard: "캔버스",
  defaultBoardEmoji: "✦",

  inspectorPrompt: "프롬프트",
  inspectorModel: "모델",
  inspectorTags: "배우고 싶은 요소",
  inspectorTagsHint: "큰 카테고리 아래에 세부 키워드를 붙이세요. 예: 카메라 앵글 → dutch tilt",
  inspectorMeta: "정보",
  inspectorReverse: "역분석",
  inspectorReverseSoon: "역분석은 2단계에서 열립니다.",
  copy: "복사",
  copied: "복사했어요",
  addTag: "요소 추가",
  tagPlaceholder: "세부 키워드",
  tagCreate: "만들기",
  tagManage: "키워드 정리",
  tagRename: "이름 바꾸기",
  tagDelete: "삭제",
  tagDeleteConfirm: (name: string) => `'${name}'을(를) 지울까요? 장에서만 떼어지고, 요소 자체는 목록에서 사라져요.`,
  tagKind: "분류",
  tagEmpty: "아직 요소가 없어요. 아래에서 만들어 보세요.",
  tagExists: "같은 이름의 요소가 이미 있어요.",
  tagFilterEmpty: "이 요소로 표시한 장이 아직 없어요.",
  viewTag: "이 요소만 보기",
  clearFilters: "필터 끄기",
  charCount: (n: number) => `${n.toLocaleString()}자`,
  dimensions: "크기",
  added: "추가일",
  board: "보드",
  group: "그룹",
  none: "없음",
  preview: "미리보기",
  modelPlaceholder: "직접 입력 · 예: Midjourney v7",
  modelRecent: "최근에 쓴 모델",

  bulkSelected: (n: number) => `${n}개 선택`,
  bulkTag: "태그",
  bulkGroup: "그룹",
  bulkMove: "보드 이동",
  bulkDelete: "삭제",
  bulkGroupSoon: "그룹은 2단계에서 열립니다.",

  undo: "실행 취소",
  deleted: (n: number) => (n === 1 ? "1장 삭제했어요" : `${n}장 삭제했어요`),
  moved: "위치를 되돌렸어요",

  uploadRejectSize: "100MB를 넘는 파일은 올릴 수 없어요.",
  uploadRejectType: "지원하지 않는 형식이에요. png jpg webp gif avif mp4 webm mov",
  duplicateAsk: "이미 있는 이미지예요 — 그래도 추가?",
  addAnyway: "추가",
  cancel: "취소",
  uploading: "올리는 중",
  pastePromptOffer: "선택한 장에 프롬프트로 붙여넣을까요?",
  pastePrompt: "프롬프트로 붙여넣기",
  pasteUrlFail: "주소를 불러오지 못했어요.",
  dropHere: "여기에 놓으면 추가됩니다",

  commandTitle: "검색",
  commandEmpty: "결과가 없어요",
  commandAssets: "에셋",
  commandTags: "태그",
  commandTerms: "용어",
  commandCharacters: "캐릭터",
  commandActions: "동작",

  noAssets: "파일을 끌어오거나 ⌘V로 붙여넣으세요",
  emptyLibrary: "아직 장이 없어요. 캔버스에서 올려 보세요.",
  fit: "맞추기",
  zoom100: "100%",

  lightbox: "원본 보기",
  close: "닫기",

  phase2: "2단계 기능이에요.",
} as const;
